[package]
name = "imc"
version = "0.6.0"
authors = ["Tiago Marques <samarques.tiago@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.12"
crc16 = "*"
clap = "2.33.0"

[lib]
name = "imc"
path = "src/lib.rs"
