//###########################################################################
// Licensed under the Apache License, Version 2.0 (the "License");          #
// you may not use this file except in compliance with the License.         #
// You may obtain a copy of the License at                                  #
//                                                                          #
// http://www.apache.org/licenses/LICENSE-2.0                               #
//                                                                          #
// Unless required by applicable law or agreed to in writing, software      #
// distributed under the License is distributed on an "AS IS" BASIS,        #
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
// See the License for the specific language governing permissions and      #
// limitations under the License.                                           #
//###########################################################################
// Author: Tiago Sá Marques                                                 #
//###########################################################################
// Automatically generated.                                                 *
//###########################################################################
// IMC XML MD5: b521199aa61f91939b6b6ed9e44d149b                            *
//###########################################################################

use crate::Header::Header;
use crate::Message::Message;
/// Base
use crate::*;

pub fn buildFrom<T: Message>(hdr: Header) -> Option<T> {
    let mut msg: T = T::new();
    if msg.id() != hdr._mgid {
        return Option::None;
    }
    msg.get_mut_header()._mgid = hdr._mgid;
    msg.get_mut_header()._sync = hdr._sync;
    msg.get_mut_header()._size = hdr._size;
    msg.get_mut_header()._timestamp = hdr._timestamp;
    msg.get_mut_header()._src = hdr._src;
    msg.get_mut_header()._src_ent = hdr._src_ent;
    msg.get_mut_header()._dst = hdr._dst;
    msg.get_mut_header()._dst_ent = hdr._dst_ent;
    Option::Some(msg)
}

pub fn build(hdr: Header) -> Option<Box<dyn Message>> {
    let ret = buildFromId(hdr._mgid);
    if ret.is_none() {
        return ret;
    }

    let mut msg = ret.unwrap();
    msg.get_mut_header()._dst = hdr._dst;
    msg.get_mut_header()._size = hdr._size;
    msg.get_mut_header()._sync = hdr._sync;
    msg.get_mut_header()._src = hdr._src;
    msg.get_mut_header()._dst_ent = hdr._dst_ent;
    msg.get_mut_header()._src_ent = hdr._src_ent;
    msg.get_mut_header()._timestamp = hdr._timestamp;

    Option::from(msg)
}

pub fn buildFromId(id: u16) -> Option<Box<dyn Message>> {
    match id {
        1 => Option::Some(Box::new(EntityState::EntityState::new())),
        2 => Option::Some(Box::new(QueryEntityState::QueryEntityState::new())),
        3 => Option::Some(Box::new(EntityInfo::EntityInfo::new())),
        4 => Option::Some(Box::new(QueryEntityInfo::QueryEntityInfo::new())),
        5 => Option::Some(Box::new(EntityList::EntityList::new())),
        7 => Option::Some(Box::new(CpuUsage::CpuUsage::new())),
        8 => Option::Some(Box::new(TransportBindings::TransportBindings::new())),
        9 => Option::Some(Box::new(RestartSystem::RestartSystem::new())),
        12 => Option::Some(Box::new(DevCalibrationControl::DevCalibrationControl::new())),
        13 => Option::Some(Box::new(DevCalibrationState::DevCalibrationState::new())),
        14 => Option::Some(Box::new(EntityActivationState::EntityActivationState::new())),
        15 => Option::Some(Box::new(
            QueryEntityActivationState::QueryEntityActivationState::new(),
        )),
        16 => Option::Some(Box::new(
            VehicleOperationalLimits::VehicleOperationalLimits::new(),
        )),
        20 => Option::Some(Box::new(MsgList::MsgList::new())),
        50 => Option::Some(Box::new(SimulatedState::SimulatedState::new())),
        51 => Option::Some(Box::new(LeakSimulation::LeakSimulation::new())),
        52 => Option::Some(Box::new(UASimulation::UASimulation::new())),
        53 => Option::Some(Box::new(DynamicsSimParam::DynamicsSimParam::new())),
        100 => Option::Some(Box::new(StorageUsage::StorageUsage::new())),
        101 => Option::Some(Box::new(CacheControl::CacheControl::new())),
        102 => Option::Some(Box::new(LoggingControl::LoggingControl::new())),
        103 => Option::Some(Box::new(LogBookEntry::LogBookEntry::new())),
        104 => Option::Some(Box::new(LogBookControl::LogBookControl::new())),
        105 => Option::Some(Box::new(ReplayControl::ReplayControl::new())),
        106 => Option::Some(Box::new(ClockControl::ClockControl::new())),
        107 => Option::Some(Box::new(HistoricCTD::HistoricCTD::new())),
        108 => Option::Some(Box::new(HistoricTelemetry::HistoricTelemetry::new())),
        109 => Option::Some(Box::new(HistoricSonarData::HistoricSonarData::new())),
        110 => Option::Some(Box::new(HistoricEvent::HistoricEvent::new())),
        111 => Option::Some(Box::new(VerticalProfile::VerticalProfile::new())),
        112 => Option::Some(Box::new(ProfileSample::ProfileSample::new())),
        150 => Option::Some(Box::new(Heartbeat::Heartbeat::new())),
        151 => Option::Some(Box::new(Announce::Announce::new())),
        152 => Option::Some(Box::new(AnnounceService::AnnounceService::new())),
        153 => Option::Some(Box::new(RSSI::RSSI::new())),
        154 => Option::Some(Box::new(VSWR::VSWR::new())),
        155 => Option::Some(Box::new(LinkLevel::LinkLevel::new())),
        156 => Option::Some(Box::new(Sms::Sms::new())),
        157 => Option::Some(Box::new(SmsTx::SmsTx::new())),
        158 => Option::Some(Box::new(SmsRx::SmsRx::new())),
        159 => Option::Some(Box::new(SmsState::SmsState::new())),
        160 => Option::Some(Box::new(TextMessage::TextMessage::new())),
        170 => Option::Some(Box::new(IridiumMsgRx::IridiumMsgRx::new())),
        171 => Option::Some(Box::new(IridiumMsgTx::IridiumMsgTx::new())),
        172 => Option::Some(Box::new(IridiumTxStatus::IridiumTxStatus::new())),
        180 => Option::Some(Box::new(GroupMembershipState::GroupMembershipState::new())),
        181 => Option::Some(Box::new(SystemGroup::SystemGroup::new())),
        182 => Option::Some(Box::new(LinkLatency::LinkLatency::new())),
        183 => Option::Some(Box::new(ExtendedRSSI::ExtendedRSSI::new())),
        184 => Option::Some(Box::new(HistoricData::HistoricData::new())),
        185 => Option::Some(Box::new(CompressedHistory::CompressedHistory::new())),
        186 => Option::Some(Box::new(HistoricSample::HistoricSample::new())),
        187 => Option::Some(Box::new(HistoricDataQuery::HistoricDataQuery::new())),
        188 => Option::Some(Box::new(RemoteCommand::RemoteCommand::new())),
        189 => Option::Some(Box::new(CommSystemsQuery::CommSystemsQuery::new())),
        190 => Option::Some(Box::new(TelemetryMsg::TelemetryMsg::new())),
        200 => Option::Some(Box::new(LblRange::LblRange::new())),
        202 => Option::Some(Box::new(LblBeacon::LblBeacon::new())),
        203 => Option::Some(Box::new(LblConfig::LblConfig::new())),
        206 => Option::Some(Box::new(AcousticMessage::AcousticMessage::new())),
        207 => Option::Some(Box::new(SimAcousticMessage::SimAcousticMessage::new())),
        211 => Option::Some(Box::new(AcousticOperation::AcousticOperation::new())),
        212 => Option::Some(Box::new(AcousticSystemsQuery::AcousticSystemsQuery::new())),
        213 => Option::Some(Box::new(AcousticSystems::AcousticSystems::new())),
        214 => Option::Some(Box::new(AcousticLink::AcousticLink::new())),
        215 => Option::Some(Box::new(AcousticRequest::AcousticRequest::new())),
        216 => Option::Some(Box::new(AcousticStatus::AcousticStatus::new())),
        217 => Option::Some(Box::new(AcousticRelease::AcousticRelease::new())),
        250 => Option::Some(Box::new(Rpm::Rpm::new())),
        251 => Option::Some(Box::new(Voltage::Voltage::new())),
        252 => Option::Some(Box::new(Current::Current::new())),
        253 => Option::Some(Box::new(GpsFix::GpsFix::new())),
        254 => Option::Some(Box::new(EulerAngles::EulerAngles::new())),
        255 => Option::Some(Box::new(EulerAnglesDelta::EulerAnglesDelta::new())),
        256 => Option::Some(Box::new(AngularVelocity::AngularVelocity::new())),
        257 => Option::Some(Box::new(Acceleration::Acceleration::new())),
        258 => Option::Some(Box::new(MagneticField::MagneticField::new())),
        259 => Option::Some(Box::new(GroundVelocity::GroundVelocity::new())),
        260 => Option::Some(Box::new(WaterVelocity::WaterVelocity::new())),
        261 => Option::Some(Box::new(VelocityDelta::VelocityDelta::new())),
        262 => Option::Some(Box::new(Distance::Distance::new())),
        263 => Option::Some(Box::new(Temperature::Temperature::new())),
        264 => Option::Some(Box::new(Pressure::Pressure::new())),
        265 => Option::Some(Box::new(Depth::Depth::new())),
        266 => Option::Some(Box::new(DepthOffset::DepthOffset::new())),
        267 => Option::Some(Box::new(SoundSpeed::SoundSpeed::new())),
        268 => Option::Some(Box::new(WaterDensity::WaterDensity::new())),
        269 => Option::Some(Box::new(Conductivity::Conductivity::new())),
        270 => Option::Some(Box::new(Salinity::Salinity::new())),
        271 => Option::Some(Box::new(WindSpeed::WindSpeed::new())),
        272 => Option::Some(Box::new(RelativeHumidity::RelativeHumidity::new())),
        273 => Option::Some(Box::new(DevDataText::DevDataText::new())),
        274 => Option::Some(Box::new(DevDataBinary::DevDataBinary::new())),
        275 => Option::Some(Box::new(Force::Force::new())),
        276 => Option::Some(Box::new(SonarData::SonarData::new())),
        277 => Option::Some(Box::new(Pulse::Pulse::new())),
        278 => Option::Some(Box::new(PulseDetectionControl::PulseDetectionControl::new())),
        279 => Option::Some(Box::new(FuelLevel::FuelLevel::new())),
        280 => Option::Some(Box::new(GpsNavData::GpsNavData::new())),
        281 => Option::Some(Box::new(ServoPosition::ServoPosition::new())),
        282 => Option::Some(Box::new(DeviceState::DeviceState::new())),
        283 => Option::Some(Box::new(BeamConfig::BeamConfig::new())),
        284 => Option::Some(Box::new(DataSanity::DataSanity::new())),
        285 => Option::Some(Box::new(RhodamineDye::RhodamineDye::new())),
        286 => Option::Some(Box::new(CrudeOil::CrudeOil::new())),
        287 => Option::Some(Box::new(FineOil::FineOil::new())),
        288 => Option::Some(Box::new(Turbidity::Turbidity::new())),
        289 => Option::Some(Box::new(Chlorophyll::Chlorophyll::new())),
        290 => Option::Some(Box::new(Fluorescein::Fluorescein::new())),
        291 => Option::Some(Box::new(Phycocyanin::Phycocyanin::new())),
        292 => Option::Some(Box::new(Phycoerythrin::Phycoerythrin::new())),
        293 => Option::Some(Box::new(GpsFixRtk::GpsFixRtk::new())),
        294 => Option::Some(Box::new(ExternalNavData::ExternalNavData::new())),
        295 => Option::Some(Box::new(DissolvedOxygen::DissolvedOxygen::new())),
        296 => Option::Some(Box::new(AirSaturation::AirSaturation::new())),
        297 => Option::Some(Box::new(Throttle::Throttle::new())),
        298 => Option::Some(Box::new(PH::PH::new())),
        299 => Option::Some(Box::new(Redox::Redox::new())),
        300 => Option::Some(Box::new(CameraZoom::CameraZoom::new())),
        301 => Option::Some(Box::new(SetThrusterActuation::SetThrusterActuation::new())),
        302 => Option::Some(Box::new(SetServoPosition::SetServoPosition::new())),
        303 => Option::Some(Box::new(
            SetControlSurfaceDeflection::SetControlSurfaceDeflection::new(),
        )),
        304 => Option::Some(Box::new(RemoteActionsRequest::RemoteActionsRequest::new())),
        305 => Option::Some(Box::new(RemoteActions::RemoteActions::new())),
        306 => Option::Some(Box::new(ButtonEvent::ButtonEvent::new())),
        307 => Option::Some(Box::new(LcdControl::LcdControl::new())),
        308 => Option::Some(Box::new(PowerOperation::PowerOperation::new())),
        309 => Option::Some(Box::new(PowerChannelControl::PowerChannelControl::new())),
        310 => Option::Some(Box::new(
            QueryPowerChannelState::QueryPowerChannelState::new(),
        )),
        311 => Option::Some(Box::new(PowerChannelState::PowerChannelState::new())),
        312 => Option::Some(Box::new(LedBrightness::LedBrightness::new())),
        313 => Option::Some(Box::new(QueryLedBrightness::QueryLedBrightness::new())),
        314 => Option::Some(Box::new(SetLedBrightness::SetLedBrightness::new())),
        315 => Option::Some(Box::new(SetPWM::SetPWM::new())),
        316 => Option::Some(Box::new(PWM::PWM::new())),
        350 => Option::Some(Box::new(EstimatedState::EstimatedState::new())),
        351 => Option::Some(Box::new(
            EstimatedStreamVelocity::EstimatedStreamVelocity::new(),
        )),
        352 => Option::Some(Box::new(IndicatedSpeed::IndicatedSpeed::new())),
        353 => Option::Some(Box::new(TrueSpeed::TrueSpeed::new())),
        354 => Option::Some(Box::new(NavigationUncertainty::NavigationUncertainty::new())),
        355 => Option::Some(Box::new(NavigationData::NavigationData::new())),
        356 => Option::Some(Box::new(GpsFixRejection::GpsFixRejection::new())),
        357 => Option::Some(Box::new(LblRangeAcceptance::LblRangeAcceptance::new())),
        358 => Option::Some(Box::new(DvlRejection::DvlRejection::new())),
        360 => Option::Some(Box::new(LblEstimate::LblEstimate::new())),
        361 => Option::Some(Box::new(AlignmentState::AlignmentState::new())),
        362 => Option::Some(Box::new(GroupStreamVelocity::GroupStreamVelocity::new())),
        363 => Option::Some(Box::new(Airflow::Airflow::new())),
        400 => Option::Some(Box::new(DesiredHeading::DesiredHeading::new())),
        401 => Option::Some(Box::new(DesiredZ::DesiredZ::new())),
        402 => Option::Some(Box::new(DesiredSpeed::DesiredSpeed::new())),
        403 => Option::Some(Box::new(DesiredRoll::DesiredRoll::new())),
        404 => Option::Some(Box::new(DesiredPitch::DesiredPitch::new())),
        405 => Option::Some(Box::new(DesiredVerticalRate::DesiredVerticalRate::new())),
        406 => Option::Some(Box::new(DesiredPath::DesiredPath::new())),
        407 => Option::Some(Box::new(DesiredControl::DesiredControl::new())),
        408 => Option::Some(Box::new(DesiredHeadingRate::DesiredHeadingRate::new())),
        409 => Option::Some(Box::new(DesiredVelocity::DesiredVelocity::new())),
        410 => Option::Some(Box::new(PathControlState::PathControlState::new())),
        411 => Option::Some(Box::new(
            AllocatedControlTorques::AllocatedControlTorques::new(),
        )),
        412 => Option::Some(Box::new(ControlParcel::ControlParcel::new())),
        413 => Option::Some(Box::new(Brake::Brake::new())),
        414 => Option::Some(Box::new(DesiredLinearState::DesiredLinearState::new())),
        415 => Option::Some(Box::new(DesiredThrottle::DesiredThrottle::new())),
        450 => Option::Some(Box::new(Goto::Goto::new())),
        451 => Option::Some(Box::new(PopUp::PopUp::new())),
        452 => Option::Some(Box::new(Teleoperation::Teleoperation::new())),
        453 => Option::Some(Box::new(Loiter::Loiter::new())),
        454 => Option::Some(Box::new(IdleManeuver::IdleManeuver::new())),
        455 => Option::Some(Box::new(LowLevelControl::LowLevelControl::new())),
        456 => Option::Some(Box::new(Rows::Rows::new())),
        457 => Option::Some(Box::new(FollowPath::FollowPath::new())),
        458 => Option::Some(Box::new(PathPoint::PathPoint::new())),
        459 => Option::Some(Box::new(YoYo::YoYo::new())),
        460 => Option::Some(Box::new(TeleoperationDone::TeleoperationDone::new())),
        461 => Option::Some(Box::new(StationKeeping::StationKeeping::new())),
        462 => Option::Some(Box::new(Elevator::Elevator::new())),
        463 => Option::Some(Box::new(FollowTrajectory::FollowTrajectory::new())),
        464 => Option::Some(Box::new(TrajectoryPoint::TrajectoryPoint::new())),
        465 => Option::Some(Box::new(CustomManeuver::CustomManeuver::new())),
        466 => Option::Some(Box::new(VehicleFormation::VehicleFormation::new())),
        467 => Option::Some(Box::new(
            VehicleFormationParticipant::VehicleFormationParticipant::new(),
        )),
        468 => Option::Some(Box::new(StopManeuver::StopManeuver::new())),
        469 => Option::Some(Box::new(RegisterManeuver::RegisterManeuver::new())),
        470 => Option::Some(Box::new(ManeuverControlState::ManeuverControlState::new())),
        471 => Option::Some(Box::new(FollowSystem::FollowSystem::new())),
        472 => Option::Some(Box::new(CommsRelay::CommsRelay::new())),
        473 => Option::Some(Box::new(CoverArea::CoverArea::new())),
        474 => Option::Some(Box::new(PolygonVertex::PolygonVertex::new())),
        475 => Option::Some(Box::new(CompassCalibration::CompassCalibration::new())),
        476 => Option::Some(Box::new(FormationParameters::FormationParameters::new())),
        477 => Option::Some(Box::new(
            FormationPlanExecution::FormationPlanExecution::new(),
        )),
        478 => Option::Some(Box::new(FollowReference::FollowReference::new())),
        479 => Option::Some(Box::new(Reference::Reference::new())),
        480 => Option::Some(Box::new(FollowRefState::FollowRefState::new())),
        481 => Option::Some(Box::new(FormationMonitor::FormationMonitor::new())),
        482 => Option::Some(Box::new(RelativeState::RelativeState::new())),
        483 => Option::Some(Box::new(Dislodge::Dislodge::new())),
        484 => Option::Some(Box::new(Formation::Formation::new())),
        485 => Option::Some(Box::new(Launch::Launch::new())),
        486 => Option::Some(Box::new(Drop::Drop::new())),
        487 => Option::Some(Box::new(ScheduledGoto::ScheduledGoto::new())),
        488 => Option::Some(Box::new(RowsCoverage::RowsCoverage::new())),
        489 => Option::Some(Box::new(Sample::Sample::new())),
        490 => Option::Some(Box::new(ImageTracking::ImageTracking::new())),
        491 => Option::Some(Box::new(Takeoff::Takeoff::new())),
        492 => Option::Some(Box::new(Land::Land::new())),
        493 => Option::Some(Box::new(AutonomousSection::AutonomousSection::new())),
        494 => Option::Some(Box::new(FollowPoint::FollowPoint::new())),
        495 => Option::Some(Box::new(Alignment::Alignment::new())),
        496 => Option::Some(Box::new(
            StationKeepingExtended::StationKeepingExtended::new(),
        )),
        497 => Option::Some(Box::new(ManeuverDone::ManeuverDone::new())),
        499 => Option::Some(Box::new(Magnetometer::Magnetometer::new())),
        500 => Option::Some(Box::new(VehicleState::VehicleState::new())),
        501 => Option::Some(Box::new(VehicleCommand::VehicleCommand::new())),
        502 => Option::Some(Box::new(MonitorEntityState::MonitorEntityState::new())),
        503 => Option::Some(Box::new(EntityMonitoringState::EntityMonitoringState::new())),
        504 => Option::Some(Box::new(OperationalLimits::OperationalLimits::new())),
        505 => Option::Some(Box::new(GetOperationalLimits::GetOperationalLimits::new())),
        506 => Option::Some(Box::new(Calibration::Calibration::new())),
        507 => Option::Some(Box::new(ControlLoops::ControlLoops::new())),
        508 => Option::Some(Box::new(VehicleMedium::VehicleMedium::new())),
        509 => Option::Some(Box::new(Collision::Collision::new())),
        510 => Option::Some(Box::new(FormState::FormState::new())),
        511 => Option::Some(Box::new(AutopilotMode::AutopilotMode::new())),
        512 => Option::Some(Box::new(FormationState::FormationState::new())),
        513 => Option::Some(Box::new(ReportControl::ReportControl::new())),
        514 => Option::Some(Box::new(StateReport::StateReport::new())),
        515 => Option::Some(Box::new(TransmissionRequest::TransmissionRequest::new())),
        516 => Option::Some(Box::new(TransmissionStatus::TransmissionStatus::new())),
        517 => Option::Some(Box::new(SmsRequest::SmsRequest::new())),
        518 => Option::Some(Box::new(SmsStatus::SmsStatus::new())),
        519 => Option::Some(Box::new(VtolState::VtolState::new())),
        520 => Option::Some(Box::new(ArmingState::ArmingState::new())),
        521 => Option::Some(Box::new(TCPRequest::TCPRequest::new())),
        522 => Option::Some(Box::new(TCPStatus::TCPStatus::new())),
        525 => Option::Some(Box::new(AssetReport::AssetReport::new())),
        550 => Option::Some(Box::new(Abort::Abort::new())),
        551 => Option::Some(Box::new(PlanSpecification::PlanSpecification::new())),
        552 => Option::Some(Box::new(PlanManeuver::PlanManeuver::new())),
        553 => Option::Some(Box::new(PlanTransition::PlanTransition::new())),
        554 => Option::Some(Box::new(EmergencyControl::EmergencyControl::new())),
        555 => Option::Some(Box::new(EmergencyControlState::EmergencyControlState::new())),
        556 => Option::Some(Box::new(PlanDB::PlanDB::new())),
        557 => Option::Some(Box::new(PlanDBState::PlanDBState::new())),
        558 => Option::Some(Box::new(PlanDBInformation::PlanDBInformation::new())),
        559 => Option::Some(Box::new(PlanControl::PlanControl::new())),
        560 => Option::Some(Box::new(PlanControlState::PlanControlState::new())),
        561 => Option::Some(Box::new(PlanVariable::PlanVariable::new())),
        562 => Option::Some(Box::new(PlanGeneration::PlanGeneration::new())),
        563 => Option::Some(Box::new(LeaderState::LeaderState::new())),
        564 => Option::Some(Box::new(PlanStatistics::PlanStatistics::new())),
        600 => Option::Some(Box::new(ReportedState::ReportedState::new())),
        601 => Option::Some(Box::new(RemoteSensorInfo::RemoteSensorInfo::new())),
        602 => Option::Some(Box::new(Map::Map::new())),
        603 => Option::Some(Box::new(MapFeature::MapFeature::new())),
        604 => Option::Some(Box::new(MapPoint::MapPoint::new())),
        606 => Option::Some(Box::new(CcuEvent::CcuEvent::new())),
        650 => Option::Some(Box::new(VehicleLinks::VehicleLinks::new())),
        651 => Option::Some(Box::new(TrexObservation::TrexObservation::new())),
        652 => Option::Some(Box::new(TrexCommand::TrexCommand::new())),
        655 => Option::Some(Box::new(TrexOperation::TrexOperation::new())),
        656 => Option::Some(Box::new(TrexAttribute::TrexAttribute::new())),
        657 => Option::Some(Box::new(TrexToken::TrexToken::new())),
        658 => Option::Some(Box::new(TrexPlan::TrexPlan::new())),
        660 => Option::Some(Box::new(Event::Event::new())),
        702 => Option::Some(Box::new(CompressedImage::CompressedImage::new())),
        703 => Option::Some(Box::new(ImageTxSettings::ImageTxSettings::new())),
        750 => Option::Some(Box::new(RemoteState::RemoteState::new())),
        800 => Option::Some(Box::new(Target::Target::new())),
        801 => Option::Some(Box::new(EntityParameter::EntityParameter::new())),
        802 => Option::Some(Box::new(EntityParameters::EntityParameters::new())),
        803 => Option::Some(Box::new(QueryEntityParameters::QueryEntityParameters::new())),
        804 => Option::Some(Box::new(SetEntityParameters::SetEntityParameters::new())),
        805 => Option::Some(Box::new(SaveEntityParameters::SaveEntityParameters::new())),
        806 => Option::Some(Box::new(CreateSession::CreateSession::new())),
        807 => Option::Some(Box::new(CloseSession::CloseSession::new())),
        808 => Option::Some(Box::new(SessionSubscription::SessionSubscription::new())),
        809 => Option::Some(Box::new(SessionKeepAlive::SessionKeepAlive::new())),
        810 => Option::Some(Box::new(SessionStatus::SessionStatus::new())),
        811 => Option::Some(Box::new(PushEntityParameters::PushEntityParameters::new())),
        812 => Option::Some(Box::new(PopEntityParameters::PopEntityParameters::new())),
        813 => Option::Some(Box::new(IoEvent::IoEvent::new())),
        814 => Option::Some(Box::new(UamTxFrame::UamTxFrame::new())),
        815 => Option::Some(Box::new(UamRxFrame::UamRxFrame::new())),
        816 => Option::Some(Box::new(UamTxStatus::UamTxStatus::new())),
        817 => Option::Some(Box::new(UamRxRange::UamRxRange::new())),
        818 => Option::Some(Box::new(UamTxRange::UamTxRange::new())),
        820 => Option::Some(Box::new(FormCtrlParam::FormCtrlParam::new())),
        821 => Option::Some(Box::new(FormationEval::FormationEval::new())),
        822 => Option::Some(Box::new(
            FormationControlParams::FormationControlParams::new(),
        )),
        823 => Option::Some(Box::new(FormationEvaluation::FormationEvaluation::new())),
        850 => Option::Some(Box::new(SoiWaypoint::SoiWaypoint::new())),
        851 => Option::Some(Box::new(SoiPlan::SoiPlan::new())),
        852 => Option::Some(Box::new(SoiCommand::SoiCommand::new())),
        853 => Option::Some(Box::new(SoiState::SoiState::new())),
        877 => Option::Some(Box::new(MessagePart::MessagePart::new())),
        888 => Option::Some(Box::new(NeptusBlob::NeptusBlob::new())),
        889 => Option::Some(Box::new(Aborted::Aborted::new())),
        890 => Option::Some(Box::new(UsblAngles::UsblAngles::new())),
        891 => Option::Some(Box::new(UsblPosition::UsblPosition::new())),
        892 => Option::Some(Box::new(UsblFix::UsblFix::new())),
        893 => Option::Some(Box::new(ParametersXml::ParametersXml::new())),
        894 => Option::Some(Box::new(GetParametersXml::GetParametersXml::new())),
        895 => Option::Some(Box::new(SetImageCoords::SetImageCoords::new())),
        896 => Option::Some(Box::new(GetImageCoords::GetImageCoords::new())),
        897 => Option::Some(Box::new(GetWorldCoordinates::GetWorldCoordinates::new())),
        898 => Option::Some(Box::new(UsblAnglesExtended::UsblAnglesExtended::new())),
        899 => Option::Some(Box::new(UsblPositionExtended::UsblPositionExtended::new())),
        900 => Option::Some(Box::new(UsblFixExtended::UsblFixExtended::new())),
        901 => Option::Some(Box::new(UsblModem::UsblModem::new())),
        902 => Option::Some(Box::new(UsblConfig::UsblConfig::new())),
        903 => Option::Some(Box::new(
            DissolvedOrganicMatter::DissolvedOrganicMatter::new(),
        )),
        904 => Option::Some(Box::new(OpticalBackscatter::OpticalBackscatter::new())),
        905 => Option::Some(Box::new(Tachograph::Tachograph::new())),
        906 => Option::Some(Box::new(ApmStatus::ApmStatus::new())),
        907 => Option::Some(Box::new(SadcReadings::SadcReadings::new())),
        908 => Option::Some(Box::new(DmsDetection::DmsDetection::new())),
        909 => Option::Some(Box::new(HomePosition::HomePosition::new())),
        1014 => Option::Some(Box::new(CurrentProfile::CurrentProfile::new())),
        1015 => Option::Some(Box::new(CurrentProfileCell::CurrentProfileCell::new())),
        1016 => Option::Some(Box::new(ADCPBeam::ADCPBeam::new())),
        2000 => Option::Some(Box::new(GpioState::GpioState::new())),
        2001 => Option::Some(Box::new(GpioStateGet::GpioStateGet::new())),
        2002 => Option::Some(Box::new(GpioStateSet::GpioStateSet::new())),
        2003 => Option::Some(Box::new(
            ColoredDissolvedOrganicMatter::ColoredDissolvedOrganicMatter::new(),
        )),
        2004 => Option::Some(Box::new(
            FluorescentDissolvedOrganicMatter::FluorescentDissolvedOrganicMatter::new(),
        )),
        2006 => Option::Some(Box::new(TotalMagIntensity::TotalMagIntensity::new())),
        2010 => Option::Some(Box::new(CommRestriction::CommRestriction::new())),
        2011 => Option::Some(Box::new(FlightEvent::FlightEvent::new())),
        2012 => Option::Some(Box::new(Scalar::Scalar::new())),
        _ => Option::None,
    }
}
